<?php

require_once 'sites/all/modules/civicrm/api/class.api.php';

function e($errno, $msg, $file, $line, $vars) {
    if(!($errno & error_reporting())) return FALSE;
    if (preg_match("/use mysqli or PDO instead/", $msg)) return FALSE;

    print "\n\n-----------------------------------------------------------------\n";
    print "Error $errno: $msg<br>\n";
    print "<pre>\n";
    $bt = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 0);
    foreach ($bt as $stack_obj) {
        $l = array_key_exists('line', $stack_obj) ? $stack_obj['line'] : "?";
        $f = array_key_exists('file', $stack_obj) ? $stack_obj['file'] : "?";
        print "$f ($l; $stack_obj[function])\n";
    }
    print "</pre>";
    die();
}
#set_error_handler('e', E_ERROR);

function write_csv($path, $data, $header) {
    print("Writing $path\n");
    $fp = fopen($path, 'w');
    fputcsv($fp, $header);
    foreach ($data as $line) {
        fputcsv($fp, $line);
    }
    fclose($fp);
}

function sync_to_constant_contact() {
    global $SITE_CONFIG;
    $mm = $SITE_CONFIG['constantcontact'];

    $tmpfname = tempnam(sys_get_temp_dir(), "contacts");
    write_csv($tmpfname, email_recipients(), array('Email address', 'First name', 'Last name'));

    $curl = curl_init("https://api.constantcontact.com/v2/activities/addcontacts?api_key=" . $mm['api_key']);
    curl_setopt($curl, CURLOPT_HTTPHEADER, array('Authorization: Bearer ' . $mm['access_token']));
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, array(
        'file_name' => 'contacts.csv',
        'lists' => '1331507544',  ## TODO get this dynamically
        'data' => new \CurlFile($tmpfname)
    ));

    if (!($curl_response = curl_exec($curl))) {
        print(curl_error($curl));
    } else {
        print($curl_response . "\n");
    }
}

function email_recipients() {
    civicrm_initialize();
    $api = new civicrm_api3();
    $api->Contact->Get(array('group' => civi_group_id('Email newsletter recipients'),
                             'sequential' => 1,
                             'rowCount' => 20000,
                             'return' => 'email,first_name,last_name'));
    $out = array();
    foreach($api->values as $c) {
        $out[] = array($c->email, $c->first_name, $c->last_name);
    }
    return $out;
}


function singer_list() {
    $api = singer_data();

    $arr = array();
    foreach($api->values as $c) {
        $arr[$c->custom_4][] = $c->display_name;
    }
    uksort($arr, "vp_sort");

    $left = '';
    $right = '';
    foreach ($arr as $vp => $p) {
        $chunk = "<strong>{$vp}</strong>:\n";

        foreach ($p as $name)
            $chunk .= "&nbsp;&nbsp;&nbsp;&nbsp;{$name}\n";

        if (preg_match('/bass|tenor/i', $vp)) {
            $right .= $chunk;
        } else {
            $left .= $chunk;
        }
    }

    return( array($left, $right) );
}

function format_phones($ph) {
    return join(
        '<br>',
        array_map(
            function($ph) {return sprintf("%s (%s)", $ph['phone'], $ph['phoneTypeId']==2 ? "Mobile" : $ph['locationType']);},
            array_filter(
                array_values($ph),
                function($ph) {return $ph['locationType'] != 'Billing';}
            )
        )
    );
}

## Get numeric group ID for given name
function civi_group_id($name) {
    $result = civicrm_api3('Group', 'get', array(
        'sequential' => 1,
        'return' => array("id"),
        'title' => $name,
    ));
    return $result['values'][0]['id'];
}

function singer_data() {
    civicrm_initialize();
    $api = new civicrm_api3();
    $api->Contact->Get(array('group' => civi_group_id('Current Singers'),
                             'sequential' => 1,
                             'rowCount' => 10000,
                             'return' => 'custom_4,display_name,email,phone,'.
                                       'street_address,city,state_province,postal_code,id',
                             'sort'=>'custom_4,last_name,first_name'));
    return $api;
}

function singer_roster2() {
    $api = singer_data();

    return array_map( function($c) {
        return array($c->custom_4,
                     sprintf("%s<br><a href=\"mailto:%s\">%s</a>",
                             $c->display_name, $c->email, $c->email),
                     format_phones(CRM_Core_BAO_Phone::allPhones($c->id)),
                     sprintf("%s<br>%s, %s %s", $c->street_address, $c->city,
                             $c->state_province, $c->postal_code)
        );
    }, $api->values);
}

function SIA_custom_token_info()
{
    $info['tokens']['sia']['singer_list_html'] = array(
        'name' => t('Singer list HTML'),
        'description' => t("A two-column formatted list of current singers in the database."),
    );
    return $info;
}

/**
 * Implements hook_tokens(). This hook replaces each token with its value.
 */
function SIA_custom_tokens($type, $tokens, array $data = array(), array $options = array()) {
    $replacements = array();
    $sanitize = !empty($options['sanitize']);

    foreach ($tokens as $name => $original) {
        if ($name == 'singer_list_html') {
            $arr = singer_list();
            $val = ("<div style=\"float:left;margin:20px\">{$arr[0]}</div>" .
                    "<div style=\"float:left;margin:20px\">{$arr[1]}</div>" .
                    "<br  style=\"clear:both\">");
            $replacements[$original] = $val;
        }
    }

    return $replacements;
}


/**
 * Implements hook_menu().
 * See http://realtidings.com/blog/12/Apr/26/drupal-commerce-custom-add-cart-link .
 */
function SIA_custom_menu() {
  $items['product/add/%/%'] =
    array(
          'page callback' => 'SIA_custom_product_add',
          'page arguments' => array(2,3),  # items 2 & 3 of the path, which come from the '%' components.
          'access arguments' => array('access content'),
          'type' => MENU_CALLBACK,
         );

  $items['donation/add'] =
    array(
          'page callback' => 'SIA_custom_donation_add',
          #'page arguments' => array(2),  # item 2 of the path, which comes from the '%' components.
          'access arguments' => array('access content'),
          'type' => MENU_CALLBACK,
         );

  return $items;
}

function render_concert($nid, $tix=true) {
 $c = node_view(node_load($nid));
 hide( $c["field_performance_date"] );
 if (!$tix) {
   hide( $c["field_ticket_info"] );
 }
 return render($c);
}

/**
 * Custom function to add donation to a cart
 */
function SIA_custom_donation_add($amount=1, $tribute='') {
  SIA_custom_product_add(9);
}

/**
 * Custom function to add product(s) to a cart by product id
 */
function SIA_custom_product_add($pid,$quantity=1) {
  if ($product = commerce_product_load($pid) ) {
    $line_item = commerce_product_line_item_new($product, $quantity);

    global $user;
    $line_item = commerce_cart_product_add($user->uid, $line_item, FALSE);
    drupal_goto('cart');
  }
}

function collapsible($title, $content, $collapsed=true) {
    return theme('ctools_collapsible', array('handle'=>$title, 'content'=>$content, 'collapsed'=>$collapsed));
}

function treatTable($title, $collapsed, $tab) {
    $content = theme('table', array('header'=> array("Date", "Bringer"), 'rows'=>$tab));
    print( collapsible($title, $content, $collapsed) );
    print( '<div clear="both"></div>' );
}

function ticketLine($desc, $id, $reserved) {
  $content = '<td style="text-align:right">'.$desc.'<br><span style="font-size:smaller">';
  $content .= $reserved ? 'Seats front &amp; center, held until showtime' : 'General admission';
  $content .= "</span></td>\n";
  $content .= '<td><a href="/product/add/'.$id.'/1"><img src="/graphics/add-to-cart.png"></a></td>';
  return $content;
}


getid3_load();

## Voice-part index
function vp_index($a) {
    $vp_order = array('soprano' => 1, 'alto' => 2, 'tenor' => 3, 'bass' => 4);
    $a = preg_replace("/ .*/", "", $a);
    $out = $vp_order[ strtolower($a) ];
    return $out;
}

## Voice-part sort
function vp_sort($a, $b) {
    $res = vp_index($a) - vp_index($b);
    if ($res) return $res;
    return strcmp($a, $b);
}


function listMP3s($files, $print=true) {
  $getID3 = new getID3;

  $result = '';

  foreach ($files as $d) {
    $f1 = preg_replace('/.*\//', '', $d);
    if (!is_dir($d)) {
      continue;
    }
    $result .= "<h3>$f1</h3>\n<ol>\n";

    $filenum = 0;
    foreach (glob("$d/*.[Mm][Pp]3") as $p) {
      $f = basename($p);
      if (!is_file($p)){
        continue;
      }
      $filenum++;

      $mp3info = $getID3->analyze($p);
      $tags = array_key_exists('tags', $mp3info) ? $mp3info['tags']['id3v2'] : array();
      $title = (array_key_exists('title',$tags) && $tags['title'][0]) ? $tags['title'][0] : "<i>$f</i>";
      $composer = (array_key_exists('composer',$tags) && $tags['composer'][0]) ?
          "<span style='font-size:smaller'>[".$tags['composer'][0]."]</span> " :
          "";
      $result .= ("<li> <a href=\"/$p\">$title</a> $composer" .
        "(".round($mp3info["filesize"]/pow(2,20), 1)."M, ".$mp3info["playtime_string"].")\n");
    }
    $result .= "</ol>\n";
  }
  if ($print) {
      print($result);
  } else {
      return($result);
  }
}

function mp3_listing($start, $end, $title, $collapsed=true, $dir='sites/default/files/reh') {

  $cache_key = 'mp3_listing'.$start.$end;
  if ($cache = cache_get($cache_key)) {
    $content = $cache->data;

  } else {

    $to_list = array();
    foreach (array_reverse(glob("$dir/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]")) as $d) {
      $f1 = substr($d, strlen($dir)+1);
      if (!is_dir($d) || strcmp($f1, $start)<0 || strcmp($f1, $end)>0) {
        continue;
      }
      $to_list[] = $d;
    }
    $content = listMP3s($to_list, false);
    cache_set($cache_key, $content, 'cache', time()+60*60); // 1 hour
  }

  print( collapsible($title, $content, $collapsed) );
}


function list_sync_check() {
    $drup_group = 'choir member';
    $did_something = false;

    $show_diffs = function($a, $b, $message) use (&$did_something) {
        $diffs = array_diff($a, $b);
        if (count($diffs) == 0) {
            return $diffs;
        }
        $did_something = true;
        print(theme_item_list(array('items' => $diffs,
                                    'title' => "$message:",
                                    'type' => 'ul',
                                    'attributes' => array())));
        return $diffs;
    };

    $get_crm = function() {
        $api = singer_data();
        $emails = array_map(function($c){return $c->email;}, $api->values);
        asort($emails);
        return $emails;
    };

    $get_drupal = function() use ($drup_group) {
        $role = user_role_load_by_name($drup_group);
        $uids = db_select('users_roles', 'ur')
            ->fields('ur', array('uid'))
            ->condition('ur.rid', $role->rid, '=')
            ->execute()
            ->fetchCol();
        $users = user_load_multiple($uids);

        $emails = array();
        foreach($users as $user) {
            $emails[] = $user->mail;
        }
        asort($emails);
        return $emails;
    };


    $get_mailman = function() {
        global $SITE_CONFIG;
        $mm = $SITE_CONFIG['mailman'];
        $cmd = sprintf("python %s --url_path /mailman/admin -c %s %s %s",
                       $mm['script'], $mm['host'], $mm['list'], $mm['password']);
        $handle = popen($cmd, "r");
        $header = fgetcsv($handle);
        if (!$handle || !$header) {
            throw new Exception("Couldn't retrieve info from MailMan");
        }

        $i = array_search("email address", $header);

        $emails = array();
        while (($data = fgetcsv($handle)) !== FALSE) {
            $emails[] = $data[$i];
        }
        asort($emails);
        return $emails;
    };

    ###################################


    $from_crm = $get_crm();
    $from_drupal = $get_drupal();
    $from_mailman = $get_mailman();

    $drup_add = $show_diffs($from_crm, $from_drupal, "Add to Drupal '$drup_group' group");
    $drup_rm  = $show_diffs($from_drupal, $from_crm, "Remove from Drupal '$drup_group' group");

    $show_diffs($from_crm, $from_mailman, "Add to MailMan list");
    $show_diffs($from_mailman, $from_crm, "Remove from MailMan list");

    if (count($drup_add) > 0) {
        print("<p>To add to Drupal: drush user-add-role 'choir member' " . join(",", $drup_add) . "</p>");
    }
    if (count($drup_rm) > 0) {
        print("<p>To remove from Drupal: drush user-remove-role 'choir member' " . join(",", $drup_rm) . "</p>");
    }

    if (!$did_something) {
        print("<p><em>Nothing!  Looks like you're good!</em></p>");
    }
}


//# Don't close with ?>
