#+TITLE: RePrev Notes
#+DATE: 11/27/2012

* Opening remarks

** Dan, Dana, and Penny are out

Mike polled us to see who can be available for Cliff Digre's service
and/or remembrance on Friday 11/30.  We could potentially be available
for both, we'll ask the family what they'd like

** Rachel is also out

Had surgery today.  Rachel is filling in as librarian.

* Look back at concert

** Feedback from David Mennicke

Jan LeClair led us through David's written remarks.  In general he was
very enthusiastic about how things went.

His requests:

- Continue to work on consistent attendance!
- Try to work on getting a full range of vocal colors
  - It's okay to not have a "signature sound"
- A picture directory would be helpful
- Would also be nice to know people's backgrounds

** Conversation about concert

Started with review of names and favorite vacation spots.  Would be
helpful to have nametags during rehearsal actually - Sheri has some
tags to share.

Schele asked people to write down reactions to debriefing questions if
they don't get a chance to speak.

*** Collaborator

Monica, Jim, Joel, Becky are positive.  Appreciated his enthusiasm,
judgment on how ambitious to be, focus on vocal health.  Warmups were
very helpful to singing well.

Sheri mentions that this literature has an easier range to sing
healthily in, compared to some folk music we've done.

Sheldon appreciates his talented musicianship.  Brent appreciated his
preparedness.

*** Literature

Several people felt strongly that too much of the music was Christian
in focus.  Some didn't feel comfortable inviting people to this
concert.  Others thought the balance was fine.

There was much discussion on this.

*** Audience

Sheri: glad that we embrace families at our concerts.

Gerald: we should reach out to Latin communities nearby for our
upcoming concert.

Jan L: we have a couple of free concert venues for our next concert,
which is helpful.

Sheri: continue to use Facebook and give names for publicity.

Kathie: didn't get publicity email (Constant Contact), we'll have to
investigate why.


** Season

Monica: could we do only 2 concerts per season?

Phil: could have really bad results on audience-building.

Schele: losing momentum could be bad for singer attrition.

Some feel concert week is very tiring - how can we help with that?

* Team reports

- Mike: among singers, 36 singers, 38 absences.  11 people never missed any.
  Average 2 people missing per rehearsal.  Important to keep up good
  attendance habits.

- Sheri: financial report.  $1840 earned through Give To The Max
  campaign.  Grant for $2200 for next concert from Rimon Foundation,
  who funds Jewish arts in the community.

- Mike: ~300 people attended concerts.  $970 donated on Saturday, $278
  on Sunday.  $4.38 donated per person.  $5825 was spent on the
  concert, $2248 taken in donations.

- Mike: tickets?  In general, free concerts haven't made huge throngs
  come to the concerts.  May diminish people's impression of our
  value.  We have decided to try selling tickets for our next concert
  that would otherwise have been free.

- Schele: thanks riser crew, reception crew, venue crew.

* February concert

Jan: little preview of next concert & schedule.  We may try to drop
one of the dress rehearsals, or move it a week earlier, to combat
fatigue.

Jan: not sure whether we'll have a reception for the February
concerts.

* Listening

Heard rough cuts of recording sessions from 2 weeks ago.

- My Spirit Sang All Day
- Blow Ye the Trumpet

Jan: please try to get here earlier next week so we can pass out music
before starting at 7:00.

